### ISSUE TITLE
JWPlayer widget failing to load required libs

### ISSUE THREAD

**Issue by MendixDev** [Andries-Smit/Mx-JW-Player#1]
Hi Andries,
I am using latest version (1.1.0) JWPlayer widget with Mendix modeler 7.13.1.
The player works fine on phone browser profile locally. However, when deployed to mendix test cloud environment it fails to load modules as below:

![capture](https://user-images.githubusercontent.com/39990223/41033590-ced074bc-69a4-11e8-9830-8e3af2560ee1.PNG)

It seems that the widget is failing to load required lib at line no. 107 of jwplayer.js and throws error at:
require(["JWPlayer/lib/free/jwplayer"], dojoLang.hitch(this, function (jwplayerFree) {

Is there anything I can modify in the widget JS?
Help needed!

**Comment by Andries-Smit** [comment]
Dear Sumit

The issue is not in the code. It is the way Mendix changed the bundling of the files.
The solution was to run
 > grunt Distribute

The newly bundled version 1.1.1 is published in the app store.

Cheers Andries
